del  backup75.png.props
del  button_stripchartpopup.png.props
del  chartlogfile.png.props
del  clientlog.png.props
del  config_AutoMate.png.props
del  Config_Automate_Server.png.props
del  config_PowerShell.png.props
del  config_Select_Automate_Task.png.props
del  config-AutoMateServer.png.props
del  configfirewall.png.props
del  config-notifier-AutoMate1.png.props
del  config-PowerShell-local.png.props
del  config-PowerShellNotifier-151001.png.props
del  config-PowerShell-remote.png.props
del  configurenotifier-alphapage.png.props
del  configurenotifier-sms.png.props
del  detailedlogging.png.props
del  DeviceList-Layer2-60pct.png.props
del  DeviceListWindow.png.props
del  dialog_addbenchmark.png.props
del  dialog_chartoptions.png.props
del  dialog_chartoptions-colortab.png.props
del  dialog_chartoptions-datatab.png.props
del  dialog_chartoptions-deletedata.png.props
del  dialog_chartoptions-editlegend.png.props
del  dialog_chartoptions-timeaxis.png.props
del  dialog_cmdlinenotifier.png.props
del  dialog_configurenotifier.png.props
del  dialog_createcsr.png.props
del  dialog_creategroup.png.props
del  dialog_editdevicelabel.png.props
del  dialog_editemailmessage.png.props
del  dialog_editnetworklabel.png.props
del  dialog_find.png.props
del  dialog_gridlayout.png.props
del  dialog_groupnotifier.png.props
del  dialog_netpagenotifier.png.props
del  dialog_register.png.props
del  dialog_setlinkspeed.png.props
del  dialog_soundnotifier.png.props
del  dialog_syslognotifier.png.props
del  dialog_trapnotifier.png.props
del  dialog_uploadcsr.png.props
del  Dlg-Autodiscovery-Scan1.png.props
del  dlg-CreateLogFile.png.props
del  dlg-EditLogFile.png.props
del  dlg-finddevice.png.props
del  Dlg-RegisterIM.png.props
del  dns-winssettings.png.props
del  EditDeviceLabel.png.props
del  EditNetworkLabel.png.props
del  emailprefs.png.props
del  eventlog.png.props
del  exportmapdata.png.props
del  freebsdlogo.gif.props
del  HelperApp-ToolsMenu.png.props
del  HelperAppWindow.png.props
del  Image136.gif.props
del  imf-filtertoolbar-exporter.PNG.props
del  imf-filtertoolbar-hosts.PNG.props
del  imf-filtertoolbar-port.PNG.props
del  imf-window-win-nice400.png.props
del  IMRS-AreaView.png.props
del  IMRS-ColumnView.png.props
del  IMRS-LineView.png.props
del  IMRS-TableView.png.props
del  InterfaceThresholds-DiscardsOutages.png.props
del  InterfaceThresholds-LinkError.png.props
del  InterfaceThresholds-LinkUtilization.png.props
del  intermapper-147x45.png.props
del  login.gif.props
del  mapdefaultdataretention.png.props
del  MapListWindow1.png.props
del  MapSettings-LeftPane.png.props
del  MapSettingsMenu.png.props
del  MapSettings-Notifiers1.png.props
del  MapWindow-NOCmap.png.props
del  Mode-lock.png.props
del  modempager-services.png.props
del  modempager-subscribers.png.props
del  notifierswindow.png.props
del  notifier-winpopup.png.props
del  outagelog.png.props
del  pane_devicedefaults.png.props
del  pane_ntservices.png.props
del  pane_remoteserver.png.props
del  pane_snmp.png.props
del  pane_ssl.png.props
del  Panel-logfiles.png.props
del  probe_ntservices.png.props
del  rename.gif.props
del  Reports-MouseOver.png.props
del  restore75.png.props
del  reverseconnection.png.props
del  RunningAnts-58.png.props
del  SendFeedback-SummaryTab.png.props
del  servercommand.png.props
del  serverconfig-telnetserver-5.5.png.props
del  serverconfig-webserver-5.5.png.props
del  serverprefs-mapcolors.png.props
del  serversettings-CreateCSR.png.props
del  serversettings-defaultdevthresholds.png.props
del  serversettings-Layer2.png.props
del  serversettings-networkdefaults.png.props
del  serversettings-SSLCertificate.png.props
del  serversettings-SSLCertificate1.png.props
del  SetProbe-demo.png.props
del  settings-smsmodems.png.props
del  settings-smsrecipients.png.props
del  solarislogo.gif.props
del  wd-Maplist-58.png.props
del  webdevlist.gif.props
del  webrefreshpopup.png.props
del  webserver-HelpMenu.png.props
del  webstripchart.gif.props
del  WelcomeMap.png.props
del  WelcomeScreen56.png.props
del  WelcomeWindo.png.props
del  window_devstatus.png.props
del  window_linkstatus.png.props
del  window_netstatus.png.props
del  window_stripchart-legendmenu.png.props
del  window_webserver-header-s.png.props
del  window-Arrange-Grid.png.props
del  window-BackupMap.png.props
del  window-BackupMap58.png.props
del  window-DevLabel.png.props
del  window-GridLayout.png.props
del  window-NetLabel.png.props
del  Window-register.png.props
del  window-RestoreMap.png.props
del  window-RestoreMap58.png.props
del  window-WebServer.png.props

pause